baseURL = 'http://example.org/'
languageCode = 'en'
defaultContentLanguage = "en"
theme = ["puppet"]
paginate = 9
hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true

title = 'Trace of life & work'

[markup]
  [markup.highlight]
  noClasses = true
  codeFences = true
  guessSyntax = true
  lineNos = true
  lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
  unsafe = true

[params]
  author = "Puppet"
  description = ""
  keywords = "blog,developer,personal"
  img_home = "nz_crop.JPG"
  img_404 = "img/404-bg.jpg"

[params.sidebar]
  enable = true
  gravatarEmail = ""
  # Overwritten by your gravatar image if `gravatarEmail` is filled
  avatar = "nz.JPG"
  bio = "a personal website"

[params.social]
  github = "memory-0318"
  linkedin = "po-lin-su-5aa213b1"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"